// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Notebook {
    /// "onb/v1"
    #[prost(string, tag = "1")]
    pub format_version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<NotebookMetadata>,
    #[prost(message, repeated, tag = "3")]
    pub cells: ::prost::alloc::vec::Vec<Cell>,
    /// Loro CRDT snapshot (binary, frontend-managed)
    #[prost(bytes = "vec", tag = "4")]
    pub crdt_snapshot: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub dag: ::core::option::Option<Dag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotebookMetadata {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    /// UUID or user identifier
    #[prost(string, tag = "3")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub created_at_unix_ms: i64,
    #[prost(int64, tag = "5")]
    pub last_modified_at_unix_ms: i64,
    /// "python" default kernel language
    #[prost(string, tag = "6")]
    pub language: ::prost::alloc::string::String,
    /// Extensible metadata
    #[prost(map = "string, string", tag = "7")]
    pub custom: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Kernel version that last saved
    #[prost(string, tag = "8")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "9")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Cell {
    /// UUID v7
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "CellKind", tag = "2")]
    pub kind: i32,
    /// Cell source code (UTF-8)
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub output: ::core::option::Option<CellOutput>,
    /// Monotonic execution counter
    #[prost(int32, tag = "5")]
    pub execution_count: i32,
    #[prost(int64, tag = "6")]
    pub last_executed_at_unix_ms: i64,
    /// Cell-level tags, custom data
    #[prost(map = "string, string", tag = "7")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(enumeration = "ExecutionStatus", tag = "8")]
    pub status: i32,
    /// "collapsed" | "expanded" | "hidden"
    #[prost(string, tag = "9")]
    pub collapsed: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CellOutput {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<OutputItem>,
    /// Last error traceback (if status == ERROR)
    #[prost(string, tag = "2")]
    pub error_traceback: ::prost::alloc::string::String,
    /// Execution duration in milliseconds
    #[prost(int64, tag = "3")]
    pub duration_ms: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutputItem {
    /// MIME type (e.g. "text/plain", "text/html", "image/png")
    #[prost(string, tag = "1")]
    pub mime_type: ::prost::alloc::string::String,
    /// Raw output data
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Text representation (for quick view)
    #[prost(string, tag = "3")]
    pub text: ::prost::alloc::string::String,
    /// Lower number = preferred renderer (0 = best)
    #[prost(int32, tag = "4")]
    pub render_priority: i32,
    /// Renderer hints (width, height, etc.)
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dag {
    /// Directed edges: upstream → downstream
    #[prost(message, repeated, tag = "1")]
    pub edges: ::prost::alloc::vec::Vec<DagEdge>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DagEdge {
    /// Upstream cell (defines variables)
    #[prost(string, tag = "1")]
    pub from_cell_id: ::prost::alloc::string::String,
    /// Downstream cell (references variables)
    #[prost(string, tag = "2")]
    pub to_cell_id: ::prost::alloc::string::String,
    /// Variables flowing through this edge
    #[prost(string, repeated, tag = "3")]
    pub variables: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KernelSnapshot {
    #[prost(string, tag = "1")]
    pub kernel_version: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub captured_at_unix_ms: i64,
    /// cell_id → cached hash + output
    #[prost(map = "string, bytes", tag = "3")]
    pub content_addressed_cache: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::vec::Vec<u8>,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attachment {
    /// UUID v7
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub size_bytes: i64,
    #[prost(bytes = "vec", tag = "5")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    /// "inline" | "file" | "s3"
    #[prost(string, tag = "6")]
    pub storage_hint: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CellKind {
    Unspecified = 0,
    Python = 1,
    Sql = 2,
    R = 3,
    Markdown = 4,
    /// Raw text (non-executable)
    Raw = 5,
}
impl CellKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CELL_KIND_UNSPECIFIED",
            Self::Python => "CELL_KIND_PYTHON",
            Self::Sql => "CELL_KIND_SQL",
            Self::R => "CELL_KIND_R",
            Self::Markdown => "CELL_KIND_MARKDOWN",
            Self::Raw => "CELL_KIND_RAW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CELL_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "CELL_KIND_PYTHON" => Some(Self::Python),
            "CELL_KIND_SQL" => Some(Self::Sql),
            "CELL_KIND_R" => Some(Self::R),
            "CELL_KIND_MARKDOWN" => Some(Self::Markdown),
            "CELL_KIND_RAW" => Some(Self::Raw),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionStatus {
    Unspecified = 0,
    Idle = 1,
    Running = 2,
    Success = 3,
    Error = 4,
    Queued = 5,
    Cancelled = 6,
}
impl ExecutionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EXECUTION_STATUS_UNSPECIFIED",
            Self::Idle => "EXECUTION_STATUS_IDLE",
            Self::Running => "EXECUTION_STATUS_RUNNING",
            Self::Success => "EXECUTION_STATUS_SUCCESS",
            Self::Error => "EXECUTION_STATUS_ERROR",
            Self::Queued => "EXECUTION_STATUS_QUEUED",
            Self::Cancelled => "EXECUTION_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXECUTION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "EXECUTION_STATUS_IDLE" => Some(Self::Idle),
            "EXECUTION_STATUS_RUNNING" => Some(Self::Running),
            "EXECUTION_STATUS_SUCCESS" => Some(Self::Success),
            "EXECUTION_STATUS_ERROR" => Some(Self::Error),
            "EXECUTION_STATUS_QUEUED" => Some(Self::Queued),
            "EXECUTION_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
